//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hostel_Managment_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allocation_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Allocation_Info()
        {
            this.Damage_Info = new HashSet<Damage_Info>();
            this.Leave_Info = new HashSet<Leave_Info>();
            this.Profile_Info = new HashSet<Profile_Info>();
        }
    
        public int Allocation_Id { get; set; }
        public string Room_NO { get; set; }
        public int Student_ID { get; set; }
    
        public virtual UserRegi UserRegi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Damage_Info> Damage_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave_Info> Leave_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profile_Info> Profile_Info { get; set; }
    }
}
