//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hostel_Managment_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Damage_Info
    {
        public int Damge_Id { get; set; }
        public string Damage_About { get; set; }
        public string Damage_Details { get; set; }
        public byte[] Damage_Proof { get; set; }
        public int Student_ID { get; set; }
        public int Room_ID { get; set; }
    
        public virtual Allocation_Info Allocation_Info { get; set; }
        public virtual UserRegi UserRegi { get; set; }
    }
}
