//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hostel_Managment_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Allocation_Info> Allocation_Info { get; set; }
        public virtual DbSet<Damage_Info> Damage_Info { get; set; }
        public virtual DbSet<Leave_Info> Leave_Info { get; set; }
        public virtual DbSet<Profile_Info> Profile_Info { get; set; }
        public virtual DbSet<UserRegi> UserRegis { get; set; }
    }
}
